// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Autocomplete: typeof import('./components/calendar/Autocomplete.vue')['default']
    AutoComplete: typeof import('./components/calendar/AutoComplete.vue')['default']
    EditCalendar: typeof import('./components/calendar/EditCalendar.vue')['default']
    FadeInOut: typeof import('./components/FadeInOut.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    LanguageBars: typeof import('./components/LanguageBars.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    PopupAlert: typeof import('./components/PopupAlert.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Template: typeof import('./components/Template.vue')['default']
    TextInput: typeof import('./components/TextInput.vue')['default']
    UserAuthForm: typeof import('./components/UserAuthForm.vue')['default']
  }
}
